import http from 'node:http'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const DIR=path.dirname(fileURLToPath(import.meta.url)), PUBLIC=path.join(DIR,'public')
const HOST=process.env.HOST||'0.0.0.0', PORT=Number(process.env.PORT||8787), IS_RENDER=process.env.RENDER==='true'
const PASSWORD=process.env.T3A_ACCESS_PASSWORD||(IS_RENDER?'':'T3A-DEMO-2026')
const SECRET=process.env.T3A_SESSION_SECRET||crypto.randomBytes(32).toString('base64url')
if(!PASSWORD){console.error('FATAL: set T3A_ACCESS_PASSWORD');process.exit(1)}

const GRID=15, WIN=5, ROLE_WEIGHT={Captain:5,Analyst:2,Core:1,Spectator:0}
const PHASE_MS={PROPOSAL:15000,VOTING:10000,EXECUTION:2500}
const rooms=new Map(), clients=new Set(), loginFails=new Map()
const now=()=>Date.now(), cellKey=(x,y)=>`${x},${y}`

// ---- private access ----
function cookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=part.slice(i+1).trim()}return out}
function sign(payload){const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');return `${body}.${sig}`}
function validSession(token){if(!token)return false;const [body,sig]=String(token).split('.');if(!body||!sig)return false;const expected=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return false;try{const p=JSON.parse(Buffer.from(body,'base64url'));return p.v===1&&p.exp>now()}catch{return false}}
function authed(req){return validSession(cookies(req).t3a_session)}
function secure(req){return IS_RENDER||String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https'}
function sessionCookie(req){const p=[`t3a_session=${sign({v:1,exp:now()+8*3600_000})}`,'Path=/','Max-Age=28800','HttpOnly','SameSite=Strict'];if(secure(req))p.push('Secure');return p.join('; ')}
function clearCookie(req){const p=['t3a_session=','Path=/','Max-Age=0','HttpOnly','SameSite=Strict'];if(secure(req))p.push('Secure');return p.join('; ')}
function samePassword(v){const a=crypto.createHash('sha256').update(String(v??'')).digest(),b=crypto.createHash('sha256').update(PASSWORD).digest();return crypto.timingSafeEqual(a,b)}
function ip(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function canLogin(addr){const t=now(),arr=(loginFails.get(addr)||[]).filter(x=>t-x<15*60_000);loginFails.set(addr,arr);return arr.length<8}
function failLogin(addr){loginFails.set(addr,[...(loginFails.get(addr)||[]),now()])}
function json(res,status,body,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(body))}
async function bodyJson(req,limit=4096){return await new Promise((resolve,reject)=>{let n=0,chunks=[];req.on('data',c=>{n+=c.length;if(n>limit){reject(new Error('Request too large'));req.destroy()}else chunks.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString()||'{}'))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}

// ---- game model ----
const newBoard=()=>Array.from({length:GRID},()=>Array(GRID).fill(null))
function safeName(v){return String(v??'').replace(/[^\p{L}\p{N} _.-]/gu,'').trim().slice(0,20)||'PLAYER'}
function validTeam(t){return ['X','O','SPECTATOR'].includes(t)}
function role(room,team){if(team==='SPECTATOR')return'Spectator';const active=[...room.players.values()].filter(p=>p.connected&&p.team===team);if(!active.some(p=>p.role==='Captain'))return'Captain';if(!active.some(p=>p.role==='Analyst'))return'Analyst';return'Core'}
function roomCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let n=0;n<100;n++){let c='';for(const b of crypto.randomBytes(6))c+=a[b%a.length];if(!rooms.has(c))return c}throw Error('No room code available')}
function event(room,text,kind='INFO'){room.events.unshift({id:crypto.randomUUID(),at:now(),text,kind});room.events=room.events.slice(0,30);room.updatedAt=now()}
function connected(room,team){return[...room.players.values()].filter(p=>p.connected&&p.team===team).length}
function canStart(room){return connected(room,'X')>0&&connected(room,'O')>0}
function clearPhase(room){room.proposals.clear();room.playerProposal.clear();room.topProposals=[];room.votes.clear();room.playerVotes.clear()}
function roomCreate(conn,name){const room={code:roomCode(),createdAt:now(),updatedAt:now(),hostId:null,board:newBoard(),phase:'WAITING',turn:'X',deadline:null,winner:null,scores:{X:0,O:0},round:1,proposals:new Map(),playerProposal:new Map(),topProposals:[],votes:new Map(),playerVotes:new Map(),players:new Map(),events:[],timer:null};rooms.set(room.code,room);roomJoin(conn,room,name,'X',true);event(room,'Arena created. Waiting for Team O.','SYSTEM');broadcast(room)}
function roomJoin(conn,room,name,team,isHost=false){if(!validTeam(team))throw Error('Invalid team');if([...room.players.values()].filter(p=>p.connected).length>=32)throw Error('Room full');leave(conn);const id=crypto.randomUUID(),p={id,name:safeName(name),team,role:role(room,team),connected:true,joinedAt:now(),conn};room.players.set(id,p);conn.roomCode=room.code;conn.playerId=id;if(isHost||!room.hostId)room.hostId=id;event(room,`${p.name} joined ${team==='SPECTATOR'?'spectators':`Team ${team}`} as ${p.role}.`,'JOIN');send(conn,{type:'joined',roomCode:room.code,playerId:id,role:p.role,team:p.team,isHost:room.hostId===id});broadcast(room)}
function leave(conn){if(!conn?.roomCode||!conn.playerId)return;const room=rooms.get(conn.roomCode),p=room?.players.get(conn.playerId);if(p){p.connected=false;p.conn=null;event(room,`${p.name} disconnected.`,'LEAVE');if(room.hostId===p.id){const next=[...room.players.values()].find(x=>x.connected&&x.team!=='SPECTATOR')||[...room.players.values()].find(x=>x.connected);room.hostId=next?.id||null;if(next)event(room,`${next.name} is now host.`,'SYSTEM')}broadcast(room)}conn.roomCode=null;conn.playerId=null}
function current(conn){const room=rooms.get(conn.roomCode);return{room,player:room?.players.get(conn.playerId)}}

function schedule(room,ms,fn){if(room.timer)clearTimeout(room.timer);room.deadline=now()+ms;room.timer=setTimeout(()=>{room.timer=null;fn(room)},ms);broadcast(room)}
function start(room){if(!canStart(room))throw Error('Need one Team X and one Team O player');room.board=newBoard();room.turn='X';room.winner=null;clearPhase(room);event(room,`Round ${room.round} started. Team X proposes first.`,'MATCH');proposalPhase(room)}
function proposalPhase(room){clearPhase(room);room.phase='PROPOSAL';event(room,`Team ${room.turn}: proposal phase.`,'PHASE');schedule(room,PHASE_MS.PROPOSAL,votingPhase)}
function randomEmpty(room){const free=[];for(let y=0;y<GRID;y++)for(let x=0;x<GRID;x++)if(!room.board[y][x])free.push({x,y});return free.length?free[Math.floor(Math.random()*free.length)]:null}
function votingPhase(room){let top=[...room.proposals.entries()].map(([k,weight])=>{const[x,y]=k.split(',').map(Number);return{x,y,proposalWeight:weight}}).sort((a,b)=>b.proposalWeight-a.proposalWeight).slice(0,3);if(!top.length){const r=randomEmpty(room);if(r)top=[{...r,proposalWeight:1}]}room.topProposals=top;room.votes.clear();room.playerVotes.clear();room.phase='VOTING';event(room,`Team ${room.turn}: top ${top.length} proposals sealed for voting.`,'PHASE');schedule(room,PHASE_MS.VOTING,executionPhase)}
function executionPhase(room){room.phase='EXECUTION';event(room,`Team ${room.turn}: vote sealed.`,'PHASE');schedule(room,PHASE_MS.EXECUTION,execute)}
function execute(room){if(!room.topProposals.length){finish(room,'DRAW');return}let best=0,bestVotes=-1,bestProposal=-1;for(let i=0;i<room.topProposals.length;i++){const v=room.votes.get(i)||0,p=room.topProposals[i].proposalWeight||0;if(v>bestVotes||(v===bestVotes&&p>bestProposal)){best=i;bestVotes=v;bestProposal=p}}const move=room.topProposals[best];if(!move||room.board[move.y]?.[move.x]){const r=randomEmpty(room);if(!r){finish(room,'DRAW');return}move.x=r.x;move.y=r.y}room.board[move.y][move.x]=room.turn;event(room,`Team ${room.turn} executed ${String.fromCharCode(65+move.x)}${move.y+1}.`,'MOVE');if(win(room.board,move.x,move.y,room.turn)){finish(room,room.turn);return}if(room.board.every(r=>r.every(Boolean))){finish(room,'DRAW');return}room.turn=room.turn==='X'?'O':'X';proposalPhase(room)}
function win(board,x,y,t){for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let s=1;s<WIN&&board[y+dy*s]?.[x+dx*s]===t;s++)n++;for(let s=1;s<WIN&&board[y-dy*s]?.[x-dx*s]===t;s++)n++;if(n>=WIN)return true}return false}
function finish(room,winner){room.phase='GAMEOVER';room.deadline=null;room.winner=winner;if(winner==='X'||winner==='O')room.scores[winner]++;event(room,winner==='DRAW'?'Round draw.':`Team ${winner} wins round ${room.round}.`,'GAMEOVER');broadcast(room)}
function nextRound(room){room.round++;start(room)}
function reset(room){if(room.timer)clearTimeout(room.timer);room.timer=null;room.round=1;room.scores={X:0,O:0};room.board=newBoard();room.phase='WAITING';room.turn='X';room.deadline=null;room.winner=null;clearPhase(room);event(room,'Match reset by host.','SYSTEM');broadcast(room)}
function propose(room,p,x,y){if(room.phase!=='PROPOSAL'||p.team!==room.turn)throw Error('Not your proposal phase');if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=GRID||y>=GRID||room.board[y][x])throw Error('Invalid cell');const w=ROLE_WEIGHT[p.role]??1,prev=room.playerProposal.get(p.id);if(prev){const n=(room.proposals.get(prev)||0)-w;n>0?room.proposals.set(prev,n):room.proposals.delete(prev)}const k=cellKey(x,y);room.proposals.set(k,(room.proposals.get(k)||0)+w);room.playerProposal.set(p.id,k);broadcast(room)}
function vote(room,p,index){if(room.phase!=='VOTING'||p.team!==room.turn)throw Error('Not your voting phase');if(!Number.isInteger(index)||index<0||index>=room.topProposals.length)throw Error('Invalid proposal');const w=ROLE_WEIGHT[p.role]??1,prev=room.playerVotes.get(p.id);if(prev!==undefined)room.votes.set(prev,Math.max(0,(room.votes.get(prev)||0)-w));room.playerVotes.set(p.id,index);room.votes.set(index,(room.votes.get(index)||0)+w);broadcast(room)}

function publicState(room,viewer){const active=viewer?.team===room.turn, spectator=viewer?.team==='SPECTATOR';const see=active||spectator;return{code:room.code,gridSize:GRID,board:room.board,phase:room.phase,turn:room.turn,deadline:room.deadline,winner:room.winner,scores:room.scores,round:room.round,hostPlayerId:room.hostId,canStart:canStart(room),players:[...room.players.values()].map(p=>({id:p.id,name:p.name,team:p.team,role:p.role,weight:ROLE_WEIGHT[p.role],connected:p.connected})),proposals:room.phase==='PROPOSAL'&&see?[...room.proposals].map(([k,weight])=>{const[x,y]=k.split(',').map(Number);return{x,y,weight}}):[],topProposals:room.topProposals,votes:room.phase==='VOTING'?(see?room.topProposals.map((_,i)=>room.votes.get(i)||0):room.topProposals.map(()=>null)):[],myProposal:viewer?room.playerProposal.get(viewer.id)||null:null,myVote:viewer?room.playerVotes.get(viewer.id)??null:null,events:room.events}}
function broadcast(room){room.updatedAt=now();for(const p of room.players.values())if(p.connected&&p.conn)send(p.conn,{type:'state',state:publicState(room,p)})}
function send(conn,obj){if(conn&&!conn.closed)conn.sendText(JSON.stringify(obj))}
function error(conn,msg){send(conn,{type:'error',message:msg})}
function message(conn,text){let m;try{m=JSON.parse(text)}catch{return error(conn,'Invalid JSON')}try{if(m.type==='create_room'){roomCreate(conn,m.name);return}if(m.type==='join_room'){const room=rooms.get(String(m.roomCode||'').toUpperCase());if(!room)throw Error('Room not found');roomJoin(conn,room,m.name,m.team||'SPECTATOR');return}const{room,player}=current(conn);if(!room||!player?.connected)throw Error('Join a room first');if(m.type==='start_match'){if(room.hostId!==player.id)throw Error('Only host can start');start(room)}else if(m.type==='next_round'){if(room.hostId!==player.id||room.phase!=='GAMEOVER')throw Error('Host can start next round after game over');nextRound(room)}else if(m.type==='reset_match'){if(room.hostId!==player.id)throw Error('Only host can reset');reset(room)}else if(m.type==='propose')propose(room,player,Number(m.x),Number(m.y));else if(m.type==='vote')vote(room,player,Number(m.index));else if(m.type==='ping')send(conn,{type:'pong',at:now()});else throw Error('Unknown action')}catch(e){error(conn,e.message)}}

// ---- minimal RFC6455 websocket ----
const GUID='258EAFA5-E914-47DA-95CA-C5AB0DC85B11'
function frame(op,payload=Buffer.alloc(0)){if(!Buffer.isBuffer(payload))payload=Buffer.from(payload);const n=payload.length;if(n<126)return Buffer.concat([Buffer.from([0x80|op,n]),payload]);if(n<=65535){const h=Buffer.alloc(4);h[0]=0x80|op;h[1]=126;h.writeUInt16BE(n,2);return Buffer.concat([h,payload])}const h=Buffer.alloc(10);h[0]=0x80|op;h[1]=127;h.writeBigUInt64BE(BigInt(n),2);return Buffer.concat([h,payload])}
function attach(socket,head){const c={socket,buffer:head?.length?Buffer.from(head):Buffer.alloc(0),closed:false,roomCode:null,playerId:null,times:[],sendText(t){if(!this.closed&&!socket.destroyed)socket.write(frame(1,t))}};clients.add(c);const consume=()=>{while(c.buffer.length>=2){const b0=c.buffer[0],b1=c.buffer[1],op=b0&15,masked=b1&128;let len=b1&127,off=2;if(!(b0&128)||!masked)return close(c,1002,'Bad frame');if(len===126){if(c.buffer.length<4)return;len=c.buffer.readUInt16BE(2);off=4}else if(len===127){if(c.buffer.length<10)return;const big=c.buffer.readBigUInt64BE(2);if(big>65536n)return close(c,1009,'Too large');len=Number(big);off=10}if(len>65536)return close(c,1009,'Too large');const total=off+4+len;if(c.buffer.length<total)return;const mask=c.buffer.subarray(off,off+4),p=Buffer.from(c.buffer.subarray(off+4,total));for(let i=0;i<p.length;i++)p[i]^=mask[i%4];c.buffer=c.buffer.subarray(total);if(op===8)return close(c,1000,'bye');if(op===9){socket.write(frame(10,p));continue}if(op!==1)continue;const t=now();c.times=c.times.filter(x=>t-x<1000);if(c.times.length>=25){error(c,'Rate limit exceeded');continue}c.times.push(t);message(c,p.toString())}};socket.on('data',d=>{c.buffer=Buffer.concat([c.buffer,d]);consume()});socket.on('close',()=>close(c));socket.on('error',()=>close(c));socket.setKeepAlive(true,30000);send(c,{type:'hello',server:'T3A Multiplayer v1.1',serverNow:now()});consume()}
function close(c,code=null,reason=''){if(!c||c.closed)return;c.closed=true;clients.delete(c);leave(c);try{if(code&&!c.socket.destroyed){const r=Buffer.from(reason).subarray(0,120),p=Buffer.alloc(2+r.length);p.writeUInt16BE(code);r.copy(p,2);c.socket.write(frame(8,p))}c.socket.end()}catch{try{c.socket.destroy()}catch{}}}

// ---- HTTP ----
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}
function lans(){const out=[];for(const[name,nets]of Object.entries(os.networkInterfaces()))for(const n of nets||[])if(n.family==='IPv4'&&!n.internal)out.push({name,address:n.address,url:`http://${n.address}:${PORT}`});return out}
async function handler(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health')return json(res,200,{ok:true,version:'1.1.0',protected:true});if(u.pathname==='/api/auth/status')return json(res,200,{authenticated:authed(req)});if(u.pathname==='/api/login'&&req.method==='POST'){const addr=ip(req);if(!canLogin(addr))return json(res,429,{ok:false,error:'Too many attempts. Try again later.'});try{const b=await bodyJson(req);if(!samePassword(b.password)){failLogin(addr);return json(res,401,{ok:false,error:'Invalid access password.'})}loginFails.delete(addr);return json(res,200,{ok:true},{'set-cookie':sessionCookie(req)})}catch(e){return json(res,400,{ok:false,error:e.message})}}if(u.pathname==='/api/logout'&&req.method==='POST')return json(res,200,{ok:true},{'set-cookie':clearCookie(req)});if(!authed(req)){return fs.readFile(path.join(PUBLIC,'login.html'),(e,d)=>{if(e){res.writeHead(503);return res.end('Login unavailable')}res.writeHead(401,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'"});res.end(d)})}if(u.pathname==='/api/info')return json(res,200,{version:'1.1.0',protected:true,port:PORT,localUrl:`http://localhost:${PORT}`,lanUrls:IS_RENDER?[]:lans()});let rel;try{rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1))}catch{res.writeHead(400);return res.end('Bad request')}if(rel==='login.html')rel='index.html';const full=path.resolve(PUBLIC,rel);if(!full.startsWith(PUBLIC+path.sep)&&full!==path.join(PUBLIC,'index.html')){res.writeHead(403);return res.end('Forbidden')}fs.readFile(full,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(full)]||'application/octet-stream','cache-control':'no-cache','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'});res.end(d)})}

const server=http.createServer(handler)
server.on('upgrade',(req,socket,head)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname!=='/ws')return socket.destroy();if(!authed(req)){socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');return socket.destroy()}const key=req.headers['sec-websocket-key'];if(!key||req.headers.upgrade?.toLowerCase()!=='websocket')return socket.destroy();const accept=crypto.createHash('sha1').update(String(key)+GUID).digest('base64');socket.write(['HTTP/1.1 101 Switching Protocols','Upgrade: websocket','Connection: Upgrade',`Sec-WebSocket-Accept: ${accept}`,'\r\n'].join('\r\n'));attach(socket,head)}catch{socket.destroy()}})
const cleanup=setInterval(()=>{const t=now();for(const[code,r]of rooms){const alive=[...r.players.values()].some(p=>p.connected),ttl=alive?6*3600_000:30*60_000;if(t-r.updatedAt>ttl){if(r.timer)clearTimeout(r.timer);rooms.delete(code)}}},60_000);cleanup.unref()
server.listen(PORT,HOST,()=>{console.log(`T3A PRIVATE MULTIPLAYER v1.1 http://localhost:${PORT}`)})
function shutdown(){for(const r of rooms.values())if(r.timer)clearTimeout(r.timer);for(const c of clients)close(c,1001,'Server shutdown');server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),2000).unref()}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown)
